name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add problem matchers
      uses: r7kamura/rust-problem-matchers@v1
    - name: Setup Rust toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Test
      run: cargo test
